import { Inter } from "next/font/google";
import "./globals.css";
import { NavigationMenu, NavigationMenuItem, NavigationMenuList } from "@/components/ui/navigation-menu";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} min-h-screen bg-slate-50 text-slate-900`}>
        {/* Background Logo */}
        <div aria-hidden="true" className="fixed inset-0 z-0 flex items-center justify-center pointer-events-none select-none">
          <img src="/cuet.png" alt="CUET Logo" className="w-2/3 max-w-2xl opacity-10 object-contain" />
        </div>
        {/* Top Navbar */}
        <nav className="relative z-10 w-full bg-white border-b border-slate-200 px-8 py-4 flex items-center justify-between shadow-sm">
          <div className="text-2xl font-bold tracking-tight">Meal Manager</div>
          <NavigationMenu>
            <NavigationMenuList className="flex flex-row gap-6">
              <NavigationMenuItem>
                <Link href="/" className="hover:text-primary transition-colors">Dashboard</Link>
              </NavigationMenuItem>
              <NavigationMenuItem>
                <Link href="/meals" className="hover:text-primary transition-colors">Meals</Link>
              </NavigationMenuItem>
              <NavigationMenuItem>
                <Link href="/profile" className="hover:text-primary transition-colors">Profile</Link>
              </NavigationMenuItem>
              {/* Add more links as needed */}
            </NavigationMenuList>
          </NavigationMenu>
        </nav>
        {/* Main Content */}
        <main className="relative z-10 p-10">
          {children}
        </main>
      </body>
    </html>
  );
}